board/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.main_page, name='home'),
    url(r'^(?P<post_id>\d+)/$', views.post_content, name="post_content"),
    url(r'^(?P<board_slug>\w+)/$', views.board_content, name='board_content'),
    url(r'^(?P<board_slug>\w+)/(?P<thread_id>\d+)/$', views.thread_content, name="thread_content"),
]

imageboard/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('board.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
from django.db import models
from django.utils import timezone
from django.db.models.signals import post_delete
from django.dispatch import receiver
import uuid
import os
from sorl.thumbnail import ImageField
from sorl.thumbnail import get_thumbnail
from django import template
from django.core.exceptions import ValidationError

def file_size(value):
    limit = 2 * 1024 * 1024
    if value.size > limit:
        raise ValidationError('File too large. Size should not exceed 2 MiB.')

register = template.Library()

from django.conf import settings
MEDIA_ROOT = settings.MEDIA_ROOT

class Board(models.Model):
	title = models.CharField(max_length=50, unique=True)
	text = models.TextField(max_length=2000)
	slug = models.SlugField(default='', max_length=15, unique=True)

	def __str__(self):
		return self.title


def handle_upload(instance, file):
	fn, fe = os.path.splitext(file)
	return os.path.join('images', str(uuid.uuid1())+fe)

class Post(models.Model):
	board = models.ForeignKey(Board, null=True, on_delete=models.CASCADE)
	parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE, related_name='answers')
	title = models.CharField(max_length=200, default='')
	comment = models.TextField(max_length=2000, blank=False)
	image = models.ImageField(upload_to=handle_upload, blank=True, validators=[file_size])
	created_date = models.DateTimeField(default=timezone.now)
	last_post_date = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.title

@receiver(post_delete, sender=Post)
def image_delete(sender, **kwargs):
	file = kwargs.get("instance")
	file.image.delete(save=False)

board/forms.py
from django.forms import ModelForm, Textarea
from .models import Board, Post, file_size
from django import forms
from nocaptcha_recaptcha.fields import NoReCaptchaField
from django.core.exceptions import ValidationError

class PostForm(forms.ModelForm):
	captcha = NoReCaptchaField()
	class Meta:
		model = Post
		fields = ('title', 'comment', 'image')
		widgets = {
			'comment':Textarea(attrs={'id' : 'comment_area_id'}),
		}

board/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Board, Post
from .forms import PostForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

def main_page(request):
	boards = Board.objects.all().order_by('title')
	return render(request, 'board/menu.html', {'boards' : boards})

def board_content(request, board_slug):
	cur_board = get_object_or_404(Board, slug=board_slug)
	if request.method == 'POST':
		form = PostForm(request.POST, request.FILES)
		if form.is_valid():
			thread = form.save(commit=False)
			print(thread.comment)
			thread.board = cur_board
			thread.parent = None
			thread.save()
			#print(form)


	boards = Board.objects.all().order_by('title')
	threads = Post.objects.filter(board = cur_board, parent =  None).order_by('-last_post_date')
	paginator = Paginator(threads, 10) # Show 25 threads per page
	page = request.GET.get('page')
	try:
		threads = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		threads = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		threads = paginator.page(paginator.num_pages)
	return render(request, 'board/board_list.html', {'boards' : boards, 'threads' : threads, 'form' : PostForm(), 'cur_board' : cur_board,})

def thread_content(request, board_slug, thread_id):
	cur_board = get_object_or_404(Board, slug=board_slug)
	cur_thread = get_object_or_404(Post, id=thread_id, board=cur_board)
	if request.method == 'POST':
		form = PostForm(request.POST, request.FILES)
		if form.is_valid():
			post = form.save(commit=False)
			post.board = cur_board
			post.parent = cur_thread
			post.save()
			cur_thread.last_post_date = post.created_date
			cur_thread.save()
	boards = Board.objects.all().order_by('title')
	posts = Post.objects.filter(parent=cur_thread).order_by('id')
	paginator = Paginator(posts, 20) # Show 25 posts per page
	page = request.GET.get('page')
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		posts = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		posts = paginator.page(paginator.num_pages)
	return render(request, 'board/thread_list.html', {'boards' : boards, 'cur_board' : cur_board, 'cur_thread' : cur_thread, 'posts' : posts, 'form' : PostForm(),})


def post_content(request, post_id):
	post = get_object_or_404(Post, id=post_id)
	print(post_id)
	return render(request, 'board/post.html', {'post' : post})

board/templates/board/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" type="text/css" href="{%static 'css/board.css'%}">
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
	<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/>
	<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
	<script src="https://www.google.com/recaptcha/api.js" async defer></script>
</head>
<body>
{%block content%}{%endblock%}
</body>
</html>

<script type="text/javascript">
	$("#dialog").dialog({ autoOpen: false, modal: false, height: "auto", width: "auto" });;

	$(".text-link").click(function() {
	    var text = $("#comment_area_id").val();
	    var id = $(this).attr('id');
	    $("#comment_area_id").val(text + ">>" + id.toString().substr(1));
		var target_top = $("#comment_area_id").offset();
		$('html, body').animate({
			scrollTop: target_top
		}, 'slow');
	})

	$("a[href ^= '#p']").mouseenter(function() {
		var link = $(this).attr('href').substr(2);
		$("#dialog").html("");
		$("#dialog").load('/' + link, function(responseTxt, statusTxt, xhr){
	        if(statusTxt == "error") {
	            $("#dialog").html("Error: " + xhr.status + ": " + xhr.statusText);
	        }
	    });
		$("#dialog").dialog("open");
	})

	$("a[href ^= '#p']").mouseleave(function() {
		var link = $(this).attr('href').substr(2);
		$("#dialog").dialog("close");
	})

	$("a[href ^= '#p']").click(function() {})

	$(".ui-dialog-titlebar").attr({"hidden" : "True"})
	$("#dialog").attr({"padding" : "0"})
</script>

board/templates/board/board_list.html
{% extends 'board/base.html' %}
{% load thumbnail %}
{% load markdown_deux_tags %}
{% load board_extras %}
{% block content %}
{%  include 'board/menu.html' %}
{% autoescape on %}
<div id="dialog"></div>
<h1>New post</h1>
 <form method="POST" class="post-form" action="{% url 'board_content' cur_board.slug%}" enctype='multipart/form-data'>{% csrf_token %}
    {% include 'board/form.html' %}
    <input type="submit" value="Submit">
</form>
<hr />

{% for thread in threads %}
	{%  include 'board/thread.html' %}

	{% for post in thread|get_posts %}
		{%  include 'board/post.html' %}
	{% endfor %}
	<hr />

{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if threads.has_previous %}
            <a href="?page={{ threads.previous_page_number }}"  class="btn btn-default">previous</a>
        {% endif %}

        {% for index in threads.paginator.num_pages|range_1_N %}
			<a href="?page={{ index }}" class="btn btn-default">{{ index }}</a>
		{% endfor %}
        
        <span class="current">
            Page {{ threads.number }} of {{ threads.paginator.num_pages }}.
        </span>

        {% if threads.has_next %}
            <a href="?page={{ threads.next_page_number }}"  class="btn btn-default">next</a>
        {% endif %}
    </span>
</div>
{% endautoescape%}
{%endblock%}

board/templates/board/form.html
<div class = "postarea">
	<table width="1%">
	<tbody>
		<tr>
			<td class="postblock" for="id_title">Title</td>
			<td>
				<input id="id_title" maxlength="200" name="title" type="text" required="">
			</td>
		</tr>
		<tr>
			<td class="postblock" for="comment_area_id">Comment:</td>
			<td><textarea cols="40" id="comment_area_id" maxlength="2000" name="comment" rows="10" required=""></textarea></td>
		</tr>
		<tr>
			<td class="postblock" for="id_image">Image:</td>
			<td><input name="image" type="file" id="id_image" size="40" accept="image/*">   </td>
		</tr>
		<tr>
			<td class="postblock" for="id_captcha">Captcha:</td>
			<td class="g-recaptcha" data-sitekey="6LedwwcUAAAAAJltf1i7LLXA6sejXFqpd2UZRsaj"></td>
		</tr>
	</tbody>
	</table>
</div>

board/templates/board/menu.html
<div class ="adminbar">
<span><a href="{% url 'home' %}">Home</a></span>  
{%for board in boards%}
	<span><a href="{% url 'board_content' board.slug %}">{{board}}</a></span> 
{%endfor%}
</div>

board/templates/board/post.html
{% load thumbnail %}
{% load markdown_deux_tags %}
{% load board_extras %}
{% autoescape on %}
<table>
<tbody>
<tr class="reply">
	<td>
		{% if post.image %}
			<a href="{{post.image.url}}">{%thumbnail post.image "300x200" crop="center" as im%}<img src='{{im.url}}' class="thumb">{%endthumbnail%}</a>
		{% endif %}
		
	</td>
	<td>
		<div><strong>{{post.title}}</strong> on {{post.created_date}} <a class="text-link" id = "p{{post.id}}" href="#id_comment">№{{post.id}}</a> </div> 
		<blockquote>{{post.comment|post_links|safe}}</blockquote>
	</td>
</tr>
</tbody>
</table>
{% endautoescape %}

board/templates/board/thread.html
{% load thumbnail %}
{% load markdown_deux_tags %}
{% load board_extras %}
{% autoescape on %}
	<div class="thread">
		<div class="data"><strong>{{thread.title}}</strong> on {{thread.created_date}}<a id ="p{{thread.id}}" class="text-link" href="#id_comment">№{{thread.id}}</a> [<a href="{% url 'thread_content' cur_board.slug thread.id%}">Ответ</a>]</div>
		{% if thread.image %}
			<a href="{{thread.image.url}}">{%thumbnail thread.image "300x200" crop="center" as im%}<img src='{{im.url}}' class="thumb">{%endthumbnail%}</a>
		{% endif %}
		<blockquote>{{thread.comment|post_links|safe}}</blockquote>
	</div>
{% endautoescape %}

board/templates/board/thread_list.html
{% extends 'board/base.html' %}
{% load thumbnail %}
{% load markdown_deux_tags %}
{% load board_extras %}
{% block content %}
{%  include 'board/menu.html' %}
{% autoescape on %}
<div id="dialog"></div>

<h1>New post</h1>
 <form method="POST" class="post-form" action="{% url 'thread_content' cur_board.slug cur_thread.id%}" enctype='multipart/form-data'>{% csrf_token %}
    {% include 'board/form.html' %}
    <input type="submit" value="Submit">
</form>
<hr />

	<div class="thread">
		<div class="data"><strong>{{cur_thread.title}}</strong> on {{cur_thread.created_date}} <span class="reflink"><a id ="p{{cur_thread.id}}" class="text-link" href="#id_comment">№{{cur_thread.id}}</a> </span>[<a href="{% url 'thread_content' cur_board.slug cur_thread.id%}">Ответ</a>]</div>
		{% if cur_thread.image %}
			<a href="{{cur_thread.image.url}}">{%thumbnail cur_thread.image "300x200" crop="center" as im%}<img src='{{im.url}}' class="thumb">{%endthumbnail%}</a>
		{% endif %}
		<blockquote>{{cur_thread.comment|post_links|safe}}</blockquote>
		<br clear="all" />
	</div>

{% for post in posts %}
	{%  include 'board/post.html' %}
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if posts.has_previous %}
            <button href="?page={{ posts.previous_page_number }}" class="btn btn-default")'>previous</button> 
        {% endif %}


        {% for index in posts.paginator.num_pages|range_1_N %}
			<a href="?page={{ index }}" class="btn btn-default">{{ index }}</a>
		{% endfor %}


        {% if posts.has_next %}
            <a href="?page={{ posts.next_page_number }}" class="btn btn-default">next</a>
        {% endif %}

        <span class="current">
            Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
        </span>
    </span>
</div>
{% endautoescape %}
{%endblock%}